version: '2'

services:
  jenkins:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - DOCKER_HOST=tcp://host.docker.internal:2375  
    ports:
      - "49001:8080"
      - "50000:50000"
    volumes:
      - ../tests/:/mnt/tests
      - ../reports/:/mnt/reports
      - ../jenkins_data:/var/jenkins_home
      - ../home:/home